HospitalProject/Models/FindSpecialist.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HospitalProject.Models
{
    public class FindSpecialist
    {
        [Key]
        public int SpecialistID { get; set; }

        [Required, StringLength(50), Display(Name = "First Name")]
        public string SpecialistFName { get; set; }

        [Required, StringLength(50), Display(Name = "Last Name")]
        public string SpecialistLName { get; set; }

        [Required, Display(Name ="Phone Number")]
        public int Phone { get; set; }

        [Required, StringLength(10), Display(Name ="Gender") ]
        public string Gender { get; set; }

        [Required, StringLength(30), Display(Name = "Speciality")]
        public string Speciality { get; set; }

        [Required, Display(Name ="Available Day")]
        public DayOfWeek AvailableDay { get; set; }

        [Required, Display(Name ="Available Time")]
        public DateTime AvailableTime { get; set; }


    }
}

HospitalProject/Controllers/FindSpecialistController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data.SqlClient;
using System.Net;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using HospitalProject.Models;
using HospitalProject.Data;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;

namespace HospitalProject.Controllers
{
    public class FindSpecialistController : Controller
    {
        private readonly HospitalDbContext db;

        public FindSpecialistController(HospitalDbContext context)
        {
            db = context;
        }

        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult List (int pagenum)
        {
            var _specialists = db.FindSpecialists.ToList();
            int specialistcount = _specialists.Count();
            int perpage = 3;
            int maxpage = (int)Math.Ceiling((decimal)specialistcount/perpage) - 1;
            if (maxpage < 0) maxpage = 0;
            if (pagenum < 0) pagenum = 0;
            if (pagenum > maxpage) pagenum = maxpage;
            int start = perpage * pagenum;
            ViewData["pagenum"] = (int)pagenum;
            ViewData["PaginationSummary"] = "";
            if ( maxpage > 0 )
            {
                ViewData["PaginationSummary"] = (pagenum + 1).ToString() + " of " + (maxpage + 1).ToString();

            }
            List<FindSpecialist> findSpecialists = db.FindSpecialists.Skip(start).Take(perpage).ToList();
            return View(findSpecialists);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("SpecialistFName, SpecialistLName, Phone, Gender, Speciality, AvailableDay, AvailableTime")] FindSpecialist findSpecialist)
        {
            if (ModelState.IsValid)
            {
                db.FindSpecialists.Add(findSpecialist);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(findSpecialist);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind("SpecialistID,SpecialistFName,SpecialistLName,Phone,Gender,Speciality,AvailableDay,AvailableTime")] FindSpecialist findSpecialist)
        {

            if (ModelState.IsValid)
            {
                db.Entry(findSpecialist).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(findSpecialist);
        }


        public ActionResult Edit(int? id)
        {
            if( id == null)
            {
                return new StatusCodeResult(400);
            }
            FindSpecialist findSpecialist = db.FindSpecialists.Find(id);
            if ( findSpecialist == null)
            {
                return NotFound();
            }
            return View(findSpecialist);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new StatusCodeResult(400);
            }
            FindSpecialist findSpecialist = db.FindSpecialists.Find(id);
            if (findSpecialist == null)
            {
                return NotFound();
            }
            return View(findSpecialist);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new StatusCodeResult(400);
            }
            FindSpecialist findSpecialist = db.FindSpecialists.Find(id);
            if (findSpecialist == null)
            {
                return NotFound();
            }

            return View(findSpecialist);
        }

        /* This action is to delete a country from the Country Table after pressing submit button
         and return to Country/Index
        */
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FindSpecialist findSpecialist = db.FindSpecialists.Find(id);
            db.FindSpecialists.Remove(findSpecialist);
            db.SaveChanges();
            return RedirectToAction("Index"); // To go back to Country/Index 

        }

    }
}

HospitalProject/Views/FindSpecialist/Create.cshtml
@model HospitalProject.Models.FindSpecialist

@{
    ViewData["Title"] = "Create";
}

<h2>Add a Specialist</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h3>Specialist</h3>

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.SpecialistFName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SpecialistFName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SpecialistFName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SpecialistLName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SpecialistLName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SpecialistLName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Speciality, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Speciality, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Speciality, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.AvailableDay, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AvailableDay, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AvailableDay, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.AvailableTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AvailableTime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AvailableTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HospitalProject/Views/FindSpecialist/Delete.cshtml
@model HospitalProject.Models.FindSpecialist
@{
    ViewData["Title"] = "Delete";
}
<div class="title">
    <h2>Delete</h2>

    <h3>Are you sure you want to Delete this Specialist?</h3>
</div>

<div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="center">
            <input type="submit" value="Delete" id="submit" />
        </div>
        <div class="center">
            <button class="buttonLink">@Html.ActionLink("Back to Specialist list", "Index")</button>
        </div>
    }
</div>

HospitalProject/Views/FindSpecialist/Details.cshtml
@model HospitalProject.Models.FindSpecialist
@{
    ViewData["Title"] = "Details";
}

<div class="title">
    <h2>Details</h2>
    <div class="row">
        <div class="col-md-12" style="border: 1px solid #cecece; border-radius:15px;">
            <div>
                <div class="label">
                    @Html.DisplayNameFor(model => model.SpecialistFName):
                </div>
                <div class="right-side">
                    @Html.DisplayFor(model => model.SpecialistFName)
                </div>
            </div>
            <div>
                <div class="label">
                    @Html.DisplayNameFor(model => model.SpecialistLName):
                </div>
                <div class="right-side">
                    @Html.DisplayFor(model => model.SpecialistLName)
                </div>
            </div>
            <div>
                <div class="label">
                    @Html.DisplayNameFor(model => model.Phone):
                </div>
                <div class="right-side">
                    @Html.DisplayFor(model => model.Phone)
                </div>
            </div>
            <div>
                <div class="label">
                    @Html.DisplayNameFor(model => model.Gender):
                </div>
                <div class="right-side">
                    @Html.DisplayFor(model => model.Gender)
                </div>
            </div>
            <div>
                <div class="label">
                    @Html.DisplayNameFor(model => model.Speciality):
                </div>
                <div class="right-side">
                    @Html.DisplayFor(model => model.Speciality)
                </div>
            </div>
            <div>
                <div class="label">
                    @Html.DisplayNameFor(model => model.AvailableDay):
                </div>
                <div class="right-side">
                    @Html.DisplayFor(model => model.AvailableDay)
                </div>
            </div>
            <div>
                <div class="label">
                    @Html.DisplayNameFor(model => model.AvailableTime):
                </div>
                <div class="right-side">
                    @Html.DisplayFor(model => model.AvailableTime)
                </div>
            </div>

            <div>
                <button class="buttonLink">@Html.ActionLink("Back to Specialist List", "Index")</button>
            </div>
        </div>
     </div>
</div>

HospitalProject/Views/FindSpecialist/Edit.cshtml
@model HospitalProject.Models.FindSpecialist
@{
    ViewData["Title"] = "Edit";
}

<h2 class="title">Edit @Html.DisplayFor(model => model.SpecialistFName) @Html.DisplayFor(model => model.SpecialistLName)</h2>


@using (Html.BeginForm("Edit", "FindSpecialist", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Specialist</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <!--Don't forget this one-->
    @Html.HiddenFor(model => model.SpecialistID)
    <div class="form-group">
        @Html.LabelFor(model => model.SpecialistFName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SpecialistFName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SpecialistFName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SpecialistLName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SpecialistLName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SpecialistLName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Speciality, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Speciality, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Speciality, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AvailableDay, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AvailableDay, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AvailableDay, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AvailableTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AvailableTime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AvailableTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HospitalProject/Views/FindSpecialist/Index.cshtml
@model IEnumerable<HospitalProject.Models.FindSpecialist>
@{
    ViewData["Title"] = "Index";
}

<h2 class="title">Index</h2>

<div class="title btn-md">@Html.ActionLink("Add a Specialist", "Create")</div>

<div class="reccontainer" style="overflow:hidden;">
    <div>@ViewData["PaginationSummary"]
    @Html.ActionLink("Prev","List","FindSpecialist", new { pagenum = ((int)ViewData["pagenum"] - 1)  }
    ) | @Html.ActionLink("Next","List","Findpecialist", new { pagenum = ((int)ViewData["pagenum"]+1) }
    )

    </div>

</div>

<div class="row">
    @foreach (var item in Model)
    {
    <div class="col-md-12" style="border: 1px solid #cecece; border-radius:15px; margin: 10px;">
        <div>
            <div class="label">
                @Html.DisplayNameFor(model => model.SpecialistFName):
            </div>
            <div class="right-side">
                @Html.DisplayFor(modelItem => item.SpecialistFName)
            </div>
        </div>
        <div>
            <div class="label">
                @Html.DisplayNameFor(model => model.SpecialistLName):
            </div>
            <div class="right-side">
                @Html.DisplayFor(modelItem => item.SpecialistLName)
            </div>
        </div>
        <div>
            <div class="label">
                @Html.DisplayNameFor(model => model.Phone):
            </div>
            <div class="right-side">
                @Html.DisplayFor(modelItem => item.Phone)
            </div>
        </div>
        <div>
            <div class="label">
                @Html.DisplayNameFor(model => model.Gender):
            </div>
            <div class="right-side">
                @Html.DisplayFor(modelItem => item.Gender)
            </div>
        </div>
        <div>
            <div class="label">
                @Html.DisplayNameFor(model => model.Speciality):
            </div>
            <div class="right-side">
                @Html.DisplayFor(modelItem => item.Speciality)
            </div>
        </div>
        <div>
            <div class="label">
                @Html.DisplayNameFor(model => model.AvailableDay):
            </div>
            <div class="right-side">
                @Html.DisplayFor(modelItem => item.AvailableDay)
            </div>
        </div>
        <div>
            <div class="label">
                @Html.DisplayNameFor(model => model.AvailableTime):
            </div>
            <div class="right-side">
                @Html.DisplayFor(modelItem => item.AvailableTime)
            </div>
        </div>
        <div>
            <div class="center">
                <button class="buttonLink">@Html.ActionLink("Edit", "Edit", new { id = item.SpecialistID })</button>
                <button class="buttonLink">@Html.ActionLink("Details", "Details", new { id = item.SpecialistID })</button>
                <button class="buttonLink">@Html.ActionLink("Delete", "Delete", new { id = item.SpecialistID })</button>
            </div>
        </div>
    </div>

    }
</div>

HospitalProject/Views/FindSpecialist/List.cshtml
@model IEnumerable<HospitalProject.Models.FindSpecialist>
@{
    ViewData["Title"] = "Index";
}

<h2 class="title">Index</h2>

<div class="title btn-md">@Html.ActionLink("Add a Specialist", "Create")</div>

<div class="reccontainer" style="overflow:hidden;">
    <div>
        @ViewData["PaginationSummary"]
    @Html.ActionLink("Prev","List","FindSpecialist", new { pagenum = ((int)ViewData["pagenum"] - 1)  }
    ) | @Html.ActionLink("Next","List","FindSpecialist", new { pagenum = ((int)ViewData["pagenum"]+1) }
)

</div>

</div>

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-12" style="border: 1px solid #cecece; border-radius:15px; margin: 10px;">
            <div>
                <div class="label">
                    @Html.DisplayNameFor(model => model.SpecialistFName):
                </div>
                <div class="right-side">
                    @Html.DisplayFor(modelItem => item.SpecialistFName)
                </div>
            </div>
            <div>
                <div class="label">
                    @Html.DisplayNameFor(model => model.SpecialistLName):
                </div>
                <div class="right-side">
                    @Html.DisplayFor(modelItem => item.SpecialistLName)
                </div>
            </div>
            <div>
                <div class="label">
                    @Html.DisplayNameFor(model => model.Phone):
                </div>
                <div class="right-side">
                    @Html.DisplayFor(modelItem => item.Phone)
                </div>
            </div>
            <div>
                <div class="label">
                    @Html.DisplayNameFor(model => model.Gender):
                </div>
                <div class="right-side">
                    @Html.DisplayFor(modelItem => item.Gender)
                </div>
            </div>
            <div>
                <div class="label">
                    @Html.DisplayNameFor(model => model.Speciality):
                </div>
                <div class="right-side">
                    @Html.DisplayFor(modelItem => item.Speciality)
                </div>
            </div>
            <div>
                <div class="label">
                    @Html.DisplayNameFor(model => model.AvailableDay):
                </div>
                <div class="right-side">
                    @Html.DisplayFor(modelItem => item.AvailableDay)
                </div>
            </div>
            <div>
                <div class="label">
                    @Html.DisplayNameFor(model => model.AvailableTime):
                </div>
                <div class="right-side">
                    @Html.DisplayFor(modelItem => item.AvailableTime)
                </div>
            </div>
            <div>
                <div class="center">
                    <button class="buttonLink">@Html.ActionLink("Edit", "Edit", new { id = item.SpecialistID })</button>
                    <button class="buttonLink">@Html.ActionLink("Details", "Details", new { id = item.SpecialistID })</button>
                    <button class="buttonLink">@Html.ActionLink("Delete", "Delete", new { id = item.SpecialistID })</button>
                </div>
            </div>
        </div>

    }
</div>